version: "3.8"
services:
   

  app:
    build: 
      context: .
    container_name: "datacraft-docker"
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    env_file:
       - .env
           