name: GitHub Actions Demo
on: 
  push:
    branches: [master]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run : docker build  -t axreki/dockecraft:${{ github.sha }} .


    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME_BIS }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   

    - name : Push to Docker Hub
      run: docker push axreki/dockercraft:${{ github.sha }}


    - uses: azure/webapps-deploy@v2
      name: Publish to Azure App 
      with: 
        app-name: datacraft-streamlit-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BIS }}
        images: 'axreki/dockercraft:${{ github.sha }}'