name: Docker Image CI

on:
  push:
    branches: [ master ] 


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install pytest
      run: pip install pytest
    - name: testing
      run: pytest

  build:
    needs: pytest
    runs-on: ubuntu-latest


    #  ___      _ _    _      _         _             _                     
    # | _ )_  _(_) |__| |  __| |___  __| |_____ _ _  (_)_ __  __ _ __ _ ___ 
    # | _ \ || | | / _` | / _` / _ \/ _| / / -_) '_| | | '  \/ _` / _` / -_)
    # |___/\_,_|_|_\__,_| \__,_\___/\__|_\_\___|_|   |_|_|_|_\__,_\__, \___|
    #                                                             |___/     
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag axreki/dockercraft-githubactions:${{ github.sha }}

  
    #  _              _        _         ___          _             _  _      _    
    # | |   ___  __ _(_)_ _   | |_ ___  |   \ ___  __| |_____ _ _  | || |_  _| |__ 
    # | |__/ _ \/ _` | | ' \  |  _/ _ \ | |) / _ \/ _| / / -_) '_| | __ | || | '_ \
    # |____\___/\__, |_|_||_|  \__\___/ |___/\___/\__|_\_\___|_|   |_||_|\_,_|_.__/
    #           |___/                                                              
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      

    #  ___         _      _   _          ___          _             _                     
    # | _ \_  _ __| |_   | |_| |_  ___  |   \ ___  __| |_____ _ _  (_)_ __  __ _ __ _ ___ 
    # |  _/ || (_-< ' \  |  _| ' \/ -_) | |) / _ \/ _| / / -_) '_| | | '  \/ _` / _` / -_)
    # |_|  \_,_/__/_||_|  \__|_||_\___| |___/\___/\__|_\_\___|_|   |_|_|_|_\__,_\__, \___|
    #                                                                           |___/     
    - name: Push the Docker image 
      run: docker push axreki/dockercraft-githubactions:${{ github.sha }}
      

    #  ___      _    _ _    _      _           _                        _             
    # | _ \_  _| |__| (_)__| |_   | |_ ___    /_\   ____  _ _ _ ___    /_\  _ __ _ __ 
    # |  _/ || | '_ \ | (_-< ' \  |  _/ _ \  / _ \ |_ / || | '_/ -_)  / _ \| '_ \ '_ \
    # |_|  \_,_|_.__/_|_/__/_||_|  \__\___/ /_/ \_\/__|\_,_|_| \___| /_/ \_\ .__/ .__/
    #                                                                      |_|  |_|   
    - uses: azure/webapps-deploy@v2
      name: Publish to Azure App
      with:
        app-name: 'ekitrnfr-sbx-lasp-03-datacraft'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'axreki/dockercraft-githubactions:${{ github.sha }}'